version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'Iwate_container'
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: first_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: